version: '2'
services:
  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
  db:
    image: mysql:8.0.15
    restart: always
    ports:
      - 53306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: testdb
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_general_ci,
      --default-storage-engine=innodb
    ]
  elasticsearch:
    image: elasticsearch:7.6.2
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    expose:
      - 9300
    environment:
      - cluster.name=ES
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - ELASTIC_PASSWORD=hogehoge
  kibana:
    image: kibana:7.6.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=hogehoge
