spring:
  redis:
    host: 172.17.0.1
    port: 6379
  statemachine:
    data:
      jpa:
        repositories:
          enabled: false
      mongo:
        repositories:
          enabled: false
elasticsearch:
  host: 172.17.0.1
  port: 9200
  username: "elastic"
  # password [from triela-private]
discord:
  name: "henriettaII(prod)"
  #token: [from triela-private]
  target-channel: "matanki-saito/vic3jpadvmod"
  target-guild-id: "1022767005662724096"
