spring:
  data:
    redis:
      host: localhost
      port: 6379
elasticsearch:
  host: localhost
  port: 9200
  username: "elastic"
  password: "hogehoge"
discord:
  name: "henriettaII(dev)"
  #token: [from triela-private]
