spring:
  profiles:
    active: dev
  elasticsearch:
    rest:
      uris: "${elasticsearch.host}:${elasticsearch.port}"
      username: "${elasticsearch.username}"
      password: "${elasticsearch.password}"

management:
  info:
    git:
      mode: full

