spring:
  redis:
    host: localhost
    port: 6379
  statemachine:
    data:
      jpa:
        repositories:
          enabled: false
      mongo:
        repositories:
          enabled: false
elasticsearch:
  host: localhost
  port: 9200
  username: "elastic"
  password: "hogehoge"
discord:
  name: "henriettaII(dev)"
  #token: [from triela-private]
