server:
  port: 80
  servlet:
    context-path: /
  ssl:
    enabled:
      false

spring:
  elasticsearch:
    uris: "${elasticsearch.host}:${elasticsearch.port}"
    username: "${elasticsearch.username}"
    password: "${elasticsearch.password}"
  config:
    activate:
      on-profile: dev

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
