@startuml

Actor User
participant "bot/channel"
participant henrietta
database elasticsearch
participant inserter.py
database paratranz
Actor translators

henrietta <-> "bot/channel" : websocket
activate henrietta

paratranz <- translators: trans
inserter.py <- paratranz : get data

note over inserter.py: by github actions\nper 6 hour


elasticsearch <- inserter.py : bulk insert

User -> "bot/channel" : call out henrietta
"bot/channel" -> henrietta : input text and user info
henrietta -> elasticsearch : query
henrietta <- elasticsearch : response
"bot/channel" <- henrietta
User <- "bot/channel"

@enduml
