name: deploy application

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      operation:
        description: 'deploy'
        required: false
jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: publish application docker to github packages
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          ./gradlew docker dockerPush
      - name: update version and tagging
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
      - name: Update manifests operation
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
          https://api.github.com/repos/matanki-saito/localservers/actions/workflows/update.yaml/dispatches \
          -d "{\"ref\":\"main\", \"inputs\": { \"source\":\"ente-pubblico-per-il-benessere-sociale/henrietta/deployment.yaml\", \"target\":\"spec.template.spec.containers.0.image\", \"value\":\"gnagaoka/henrietta-app:${{ steps.tag_version.outputs.new_tag }}\"}}"
