name: upload docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      operation:
        description: 'upload'
        required: false
jobs:
  build-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 21
      - name: publish application docker to github packages
        env:
          MY_GITHUB_TOKEN_FOR_DOWNLOAD_POM: ${{ secrets.MY_GITHUB_TOKEN_FOR_DOWNLOAD_POM }}
        run: |
          printenv
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          ./gradlew docker dockerPush
      - name: update version and tagging
        env:
          MY_GITHUB_TOKEN_FOR_DOWNLOAD_POM: ${{ secrets.MY_GITHUB_TOKEN_FOR_DOWNLOAD_POM }}
        run: |
          git config --local user.email "matanki.saito@gmail.com"
          git config --local user.name "matanki.saito"
          ./gradlew release -Prelease.useAutomaticVersion=true
